# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


name: cpapp
resources:
  containers:
  - container: mta
    image: 'ghcr.io/sap/mbtci-java11-node14:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged
  - container: node
    image: 'geekykaran/headless-chrome-node-docker:latest'
    options: --privileged

trigger:
- main

stages:
- stage: build
  displayName: Build MTA for SAP Cloud Platform
  jobs:
    - job: build
      container: mta
      steps:
        - bash: 'mbt --platform cf --mtar cpapp_1.0.0.mtar -t . build'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: WebApp

- stage: test
  displayName: Run Karma Test Suite
  jobs:
    - job: test
      pool:
        vmImage: 'ubuntu-latest'
      container: node
      steps:
        - bash: 'npm config set @sap:registry "https://npm.sap.com" && npm install && npm run-script test'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: TestResult


- stage: deploy
  displayName: Deployment to SAP Cloud Platform (cf)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: WebApp 
        - bash: 'cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)" && cf deploy $(Pipeline.Workspace)/WebApp/cpapp_1.0.0.mtar -f'

- stage: upload
  displayName: Upload to CTMS
  jobs:
    - job: upload
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: WebApp
        - bash: | 
            TOKEN=$(curl -s -X POST -u "sb-44ff2054-5011-4420-869d-2ae6eba0d238!b345054|alm-ts-backend!b1603:71d6e9a1-d697-48b9-8e2b-720c617c748f$p_6UvIS6SaiW2ploXcpe9aXBKV9Wkx3pwK-hyDOVnp4=" -d "grant_type=client_credentials&response_type=token" https://26c4a376trial.authentication.us10.hana.ondemand.com/oauth/token | sed -n '/ *"access_token": *"/ {s///; s/{//g ;s/".*//; p; }')
            BODY=$(curl -s --location --request POST 'https://transport-service-app-backend.ts.cfapps.us10.hana.ondemand.com/v2/files/upload' --header "Authorization: Bearer $TOKEN" --header 'Cookie: JSESSIONID=D11A4F1DE5C6638B18925D58307B360D; __VCAP_ID__=8aa9e193-d2a1-492c-76bc-288a' --form 'file=@"$(Pipeline.Workspace)/WebApp/cpapp_1.0.0.mtar"' | awk -F ":" '{print $2}' | grep -Po "\\d+")
            curl --location --request POST 'https://transport-service-app-backend.ts.cfapps.us10.hana.ondemand.com/v2/nodes/upload' --header 'Content-Type: application/json' --header "Authorization: Bearer $TOKEN" --header 'Cookie: JSESSIONID=D11A4F1DE5C6638B18925D58307B360D; __VCAP_ID__=8aa9e193-d2a1-492c-76bc-288a' --data-raw '{ "nodeName": "node2", "contentType": "MTA", "storageType": "FILE", "entries": [ { "uri": '"$BODY"' } ], "description": "desc", "namedUser": "user" }'